[package]
name = "remu"
version = "0.1.0"
edition = "2024"

[dependencies]
goblin = "0.10.7"
dynasm = "5.0.0"
dynasmrt = "5.0.0"
clap = { version = "4.6.1", features = ["derive"] }
anyhow = "1.0.102"
thiserror = "2.0.18"
smallvec = "1.15.1"
log = "0.4.31"
env_logger = "0.11.10"
hashbrown = "0.17.1"
