name: cache_cargo
description: Cache cargo registry and git
runs:
  using: composite
  steps:
    - name: Cache cargo registry
      uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
